"""Base report builder."""

from typing import Any

from jinja2 import Template

from app.core.logging import get_logger

logger = get_logger(__name__)

DEFAULT_REPORT_TEMPLATE = """# {{ title }}

**Topic:** {{ topic_name }}  
**Generated:** {{ generated_at }}  
**Organization:** {{ organization_name }}

## Executive Summary

{{ summary }}

## Analysis Results

{% for result in results %}
### {{ result.result_type | title }}

{% if result.score is not none %}**Score:** {{ result.score }}/100  {% endif %}

{{ result.summary }}

{% if result.details and result.details.analysis %}
{{ result.details.analysis }}
{% endif %}

---
{% endfor %}

## Sources

{% for source in sources %}
- **{{ source.name }}** ({{ source.source_type }})
{% endfor %}
"""


class ReportBuilder:
    """Build reports from analysis results and topic data."""

    async def build_markdown(
        self,
        *,
        title: str,
        topic_name: str,
        organization_name: str,
        summary: str,
        results: list[dict[str, Any]],
        sources: list[Any],
        generated_at: str,
    ) -> str:
        """Render a Markdown report from a Jinja template."""
        template = Template(DEFAULT_REPORT_TEMPLATE)
        return template.render(
            title=title,
            topic_name=topic_name,
            organization_name=organization_name,
            summary=summary,
            results=results,
            sources=sources,
            generated_at=generated_at,
        )

    async def build_html(self, markdown_content: str) -> str:
        """Convert Markdown report to HTML."""
        import markdown

        return markdown.markdown(markdown_content, extensions=["tables", "fenced_code"])

    async def build_docx(self, markdown_content: str, output_path: str) -> str:
        """Convert Markdown content to DOCX and save."""
        from docx import Document

        doc = Document()
        for line in markdown_content.splitlines():
            line = line.strip()
            if line.startswith("# "):
                doc.add_heading(line[2:], level=1)
            elif line.startswith("## "):
                doc.add_heading(line[3:], level=2)
            elif line.startswith("### "):
                doc.add_heading(line[4:], level=3)
            elif line:
                doc.add_paragraph(line)
        doc.save(output_path)
        return output_path

    async def build_pptx(self, title: str, slides: list[dict[str, str]], output_path: str) -> str:
        """Build a simple PPTX presentation."""
        from pptx import Presentation
        from pptx.util import Inches, Pt

        prs = Presentation()
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = title
        title_slide.placeholders[1].text = "Generated by Leafleter"

        for slide in slides:
            s = prs.slides.add_slide(prs.slide_layouts[1])
            s.shapes.title.text = slide.get("title", "")
            body = s.placeholders[1]
            tf = body.text_frame
            tf.text = slide.get("content", "")

        prs.save(output_path)
        return output_path
