"""Intelligence ingestion

Revision ID: 779ed4f4ced7
Revises: 9415e2ae0254
Create Date: 2026-06-17 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779ed4f4ced7'
down_revision = '9415e2ae0254'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'intelligence_sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=1000), nullable=True),
        sa.Column('query', sa.Text(), nullable=True),
        sa.Column('configuration', sa.JSON(), nullable=True),
        sa.Column('refresh_interval_minutes', sa.Integer(), nullable=True),
        sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('fetch_error', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('competitor_id', sa.Integer(), nullable=True),
        sa.Column('topic_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('updated_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_sources_organization_id'), 'intelligence_sources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intelligence_sources_source_type'), 'intelligence_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_intelligence_sources_competitor_id'), 'intelligence_sources', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_intelligence_sources_topic_id'), 'intelligence_sources', ['topic_id'], unique=False)

    op.create_table(
        'intelligence_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('url', sa.String(length=1000), nullable=True),
        sa.Column('source_name', sa.String(length=255), nullable=True),
        sa.Column('source_url', sa.String(length=1000), nullable=True),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.Column('sentiment', sa.String(length=20), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('entities', sa.JSON(), nullable=True),
        sa.Column('extra_metadata', sa.JSON(), nullable=True),
        sa.Column('content_hash', sa.String(length=64), nullable=False),
        sa.Column('is_noise', sa.Boolean(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=True),
        sa.Column('competitor_id', sa.Integer(), nullable=True),
        sa.Column('topic_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('updated_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_id'], ['intelligence_sources.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_items_organization_id'), 'intelligence_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intelligence_items_item_type'), 'intelligence_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_intelligence_items_content_hash'), 'intelligence_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_intelligence_items_source_id'), 'intelligence_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_intelligence_items_competitor_id'), 'intelligence_items', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_intelligence_items_topic_id'), 'intelligence_items', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_items_topic_id'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_competitor_id'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_source_id'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_content_hash'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_item_type'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_organization_id'), table_name='intelligence_items')
    op.drop_table('intelligence_items')
    op.drop_index(op.f('ix_intelligence_sources_topic_id'), table_name='intelligence_sources')
    op.drop_index(op.f('ix_intelligence_sources_competitor_id'), table_name='intelligence_sources')
    op.drop_index(op.f('ix_intelligence_sources_source_type'), table_name='intelligence_sources')
    op.drop_index(op.f('ix_intelligence_sources_organization_id'), table_name='intelligence_sources')
    op.drop_table('intelligence_sources')
    # ### end Alembic commands ###
