"""Competitor feature comparison

Revision ID: 9415e2ae0254
Revises: 3b7f51e4d511
Create Date: 2026-06-15 01:12:39.237392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9415e2ae0254'
down_revision = '3b7f51e4d511'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('competitor_snapshots', sa.Column('features', sa.JSON(), nullable=True))
    op.create_table(
        'competitor_feature_comparisons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('report_format', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('markdown_content', sa.Text(), nullable=True),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('download_url', sa.String(length=1000), nullable=True),
        sa.Column('sources', sa.JSON(), nullable=True),
        sa.Column('our_features', sa.JSON(), nullable=True),
        sa.Column('their_features', sa.JSON(), nullable=True),
        sa.Column('comparison_summary', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('competitor_id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('updated_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_feature_comparisons_competitor_id'), 'competitor_feature_comparisons', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_feature_comparisons_organization_id'), 'competitor_feature_comparisons', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_feature_comparisons_organization_id'), table_name='competitor_feature_comparisons')
    op.drop_index(op.f('ix_competitor_feature_comparisons_competitor_id'), table_name='competitor_feature_comparisons')
    op.drop_table('competitor_feature_comparisons')
    op.drop_column('competitor_snapshots', 'features')
    op.drop_column('organizations', 'features')
    # ### end Alembic commands ###
