"""Facts

Revision ID: ca8f3b2181f9
Revises: 779ed4f4ced7
Create Date: 2026-06-17 19:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8f3b2181f9'
down_revision = '779ed4f4ced7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fact_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fact_type', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('prompt', sa.Text(), nullable=True),
        sa.Column('schema_definition', sa.JSON(), nullable=True),
        sa.Column('example', sa.JSON(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('updated_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_templates_organization_id'), 'fact_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fact_templates_fact_type'), 'fact_templates', ['fact_type'], unique=False)

    op.create_table(
        'facts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fact_type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('attributes', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.String(length=20), nullable=True),
        sa.Column('evidence', sa.JSON(), nullable=True),
        sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('competitor_id', sa.Integer(), nullable=True),
        sa.Column('item_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['item_id'], ['intelligence_items.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['template_id'], ['fact_templates.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_organization_id'), 'facts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_facts_fact_type'), 'facts', ['fact_type'], unique=False)
    op.create_index(op.f('ix_facts_template_id'), 'facts', ['template_id'], unique=False)
    op.create_index(op.f('ix_facts_competitor_id'), 'facts', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_facts_item_id'), 'facts', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_item_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_competitor_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_template_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_fact_type'), table_name='facts')
    op.drop_index(op.f('ix_facts_organization_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_fact_templates_fact_type'), table_name='fact_templates')
    op.drop_index(op.f('ix_fact_templates_organization_id'), table_name='fact_templates')
    op.drop_table('fact_templates')
    # ### end Alembic commands ###
