"""Vector chunks

Revision ID: f4bf8d9e2512
Revises: ca8f3b2181f9
Create Date: 2026-06-17 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bf8d9e2512'
down_revision = 'ca8f3b2181f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vector_chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chunk_type', sa.String(length=50), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', sa.JSON(), nullable=True),
        sa.Column('embedding_model', sa.String(length=100), nullable=True),
        sa.Column('token_count', sa.Integer(), nullable=True),
        sa.Column('extra_metadata', sa.JSON(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('updated_by_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_chunks_organization_id'), 'vector_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vector_chunks_chunk_type'), 'vector_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_vector_chunks_source_id'), 'vector_chunks', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_chunks_source_id'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_chunk_type'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_organization_id'), table_name='vector_chunks')
    op.drop_table('vector_chunks')
    # ### end Alembic commands ###
